### ISSUE TITLE
Error compiling: `thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:152:26:`

### ISSUE THREAD

**Issue by josecelano** [programatik29/axum-server#151]
Active toolchain:

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.83.0-nightly (7042c269c 2024-09-23)

```output
   Compiling axum-server v0.7.1
thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:152:26:
broken MIR in Item(DefId(0:339 ~ axum_server[2cd6]::tls_rustls::future::{impl#2}::poll)) (after phase change to runtime-optimized) at bb40[2]:
Normal edge to BasicBlockData { statements: [StorageDead(_56)], terminator: Some(Terminator { source_info: SourceInfo { span: /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-server-0.7.1/src/tls_rustls/future.rs:110:17: 110:18 (#0), scope: scope[1] }, kind: goto -> bb49 }), is_cleanup: false } violates unwind invariants (cleanup true -> false)
stack backtrace:
   0:     0x7f8ed748832a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf9d4ce087fe74a0
   1:     0x7f8ed7c03666 - core::fmt::write::h6d8d6eef4a4af1ac
   2:     0x7f8ed8d25db3 - std::io::Write::write_fmt::h9c1a7b2c301e0052
   3:     0x7f8ed7488182 - std::sys::backtrace::BacktraceLock::print::h5a5be8b1e95a2bbb
   4:     0x7f8ed748a901 - std::panicking::default_hook::{{closure}}::ha72f3fa07467f26a
   5:     0x7f8ed748a734 - std::panicking::default_hook::hcc7760cf4378effc
   6:     0x7f8ed658286f - std[25b33fdea409b280]::panicking::update_hook::<alloc[1694921db2598cc8]::boxed::Box<rustc_driver_impl[91319f0e19a4d720]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7f8ed748b018 - std::panicking::rust_panic_with_hook::hfa739d875be2cf67
   8:     0x7f8ed748adea - std::panicking::begin_panic_handler::{{closure}}::h9a9134f6e05b41bd
   9:     0x7f8ed74887d9 - std::sys::backtrace::__rust_end_short_backtrace::h35fa4dfdd9fe9e0c
  10:     0x7f8ed748aaac - rust_begin_unwind
  11:     0x7f8ed4c9e7b0 - core::panicking::panic_fmt::hc3e7c6c5c469a97f
  12:     0x7f8ed52b311a - <rustc_mir_transform[2c59a960358d0625]::validate::Validator as rustc_mir_transform[2c59a960358d0625]::pass_manager::MirPass>::run_pass
  13:     0x7f8ed7c0dc64 - rustc_mir_transform[2c59a960358d0625]::pass_manager::run_passes_inner
  14:     0x7f8ed8603922 - rustc_mir_transform[2c59a960358d0625]::optimized_mir
  15:     0x7f8ed86021db - rustc_query_impl[16add4a89c515f02]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[16add4a89c515f02]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7f8ed7c31eae - rustc_query_system[cd92c81c02f5c019]::query::plumbing::try_execute_query::<rustc_query_impl[16add4a89c515f02]::DynamicConfig<rustc_query_system[cd92c81c02f5c019]::query::caches::DefIdCache<rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[16add4a89c515f02]::plumbing::QueryCtxt, false>
  17:     0x7f8ed7c3145f - rustc_query_impl[16add4a89c515f02]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7f8ed860e963 - rustc_middle[5962dfe9f3174182]::query::plumbing::query_get_at::<rustc_query_system[cd92c81c02f5c019]::query::caches::DefIdCache<rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>>
  19:     0x7f8ed8616305 - <rustc_metadata[bda71c6b2cfd99ea]::rmeta::encoder::EncodeContext>::encode_crate_root
  20:     0x7f8ed8cb8ad3 - rustc_metadata[bda71c6b2cfd99ea]::rmeta::encoder::encode_metadata
  21:     0x7f8ed8cc0f54 - rustc_metadata[bda71c6b2cfd99ea]::fs::encode_and_write_metadata
  22:     0x7f8ed8cbfd43 - <rustc_interface[1294e3f809d58823]::queries::Linker>::codegen_and_build_linker
  23:     0x7f8ed892a34b - rustc_interface[1294e3f809d58823]::interface::run_compiler::<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}
  24:     0x7f8ed89bf210 - std[25b33fdea409b280]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1294e3f809d58823]::util::run_in_thread_with_globals<rustc_interface[1294e3f809d58823]::util::run_in_thread_pool_with_globals<rustc_interface[1294e3f809d58823]::interface::run_compiler<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>
  25:     0x7f8ed89bf87a - <<std[25b33fdea409b280]::thread::Builder>::spawn_unchecked_<rustc_interface[1294e3f809d58823]::util::run_in_thread_with_globals<rustc_interface[1294e3f809d58823]::util::run_in_thread_pool_with_globals<rustc_interface[1294e3f809d58823]::interface::run_compiler<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#1} as core[1e18fbba9f4dcc19]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f8ed89bfc6b - std::sys::pal::unix::thread::Thread::new::thread_start::h9c0c387d4b02e16a
  27:     0x7f8ed2c8f18a - start_thread
                               at ./nptl/pthread_create.c:444:8
  28:     0x7f8ed2d1dbd0 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  29:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.
```

**Comment by josecelano** [comment]
It's now failing on a different package :-/
